insert into usuario (id, usuario, senha, nome, email, idioma) values(1,'joao', '1234', 'Joao da Silva','joaodasilva@email.com', 'pt-br');
insert into usuario (id, usuario, senha, nome, email, idioma) values(2,'maria', '1111', 'Maria dos Santos','mariasantos@email.com', 'pt-br');

insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Elsie Brett'       , '1990-01-01', null, '', true); 
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Phoenix Squires'   , '1991-01-02', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Bluebell Bateman'  , '1992-01-03', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Dione Briggs'      , '1993-01-04', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Kaelan Montes'     , '1994-01-05', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Jamel Brady'       , '1995-01-06', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Calista Blanchard' , '1996-01-07', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Rohaan Shepherd'   , '1997-01-08', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Sunny Lynch'       , '1998-01-09', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Kiri Iles'         , '1999-01-10', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Lemar Foley'       , '2001-01-11', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Aleyna Cartwright' , '2002-02-12', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Brady Mcfarland'   , '2003-02-13', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Zane Mackie'       , '2004-02-14', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Fahad Spears'      , '2005-02-15', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Chardonnay Horne'  , '2006-02-16', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Andreas Senior'    , '2007-02-17', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Hebe Miles'        , '2008-02-18', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Eman Bernal'       , '2009-02-19', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Zeeshan Herman'    , '2010-02-20', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Komal Trujillo'    , '2011-02-21', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Bridget Wolf'      , '2012-02-22', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Holly Broadhurst'  , '1980-02-23', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Hisham French'     , '1981-02-24', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Viktor England'    , '1982-03-25', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Danyal Larsen'     , '1983-03-26', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Tahlia Savage'     , '1984-03-27', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Naveed Molina'     , '1985-04-28', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Zahid Taylor'      , '1986-04-29', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Ikra Wilks'        , '1987-04-30', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Fahima Boyle'      , '1988-04-01', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Sama Mccall'       , '1989-04-02', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Fathima Mccabe'    , '1970-04-03', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Ned Bowler'        , '1971-04-04', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Yvette Hartman'    , '1972-05-05', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Silas Bean'        , '1973-05-06', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Teddie Chamberlain', '1974-05-07', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Tariq Hill'        , '1975-05-08', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Sinead Mathews'    , '1976-05-09', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Jasmin O''Reilly'  , '1977-05-10', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Shane Larson'      , '1978-05-11', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Cydney Fritz'      , '1979-05-12', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Wade Webber'       , '1980-05-13', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Rizwan Flowers'    , '1981-05-14', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Zuzanna Gilbert'   , '1982-06-15', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Agnes Hodges'      , '1983-06-16', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Stewart Cordova'   , '1984-06-17', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Sahra Shields'     , '1985-06-18', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Graeme Wade'       , '1986-06-19', null, '', true);
insert into professores (nome, data_nascimento, foto, curriculo, status) values ('Hayleigh Middleton', '1987-06-20', null, '', true);